In [3]:
    import numpy as np
    #create a sample matrix
    X=np.array([[1,2,3],[4,5,6],[7,8,9]])
    #perform SVD
    U,S,VT=np.linalg.svd(X)
    #choose the no of components to keep (eg 2)
    n_components=2
    #reconstruct the matrix with reduced dimensions
    X_reconstructed=np.dot(U[:, :n_components],np.dot(np.diag(S[:n_components]),VT[:n_components, :]))
    print("original matrix:")
    print(X)
    print("\nreconstructed matrix(with reduced dimensions):")
    print(X_reconstructed)



original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

reconstructed matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
