In [4]:
#matrix operation using numpy
import numpy as np
#create matrices
A=np.array([[2,3],[4,5]])
B=np.array([[3,2],[1,9]])
#addition
C=A+B
#substraction
D=A-B
#Multiplication(element-wise)
E=A*B
#Matrix multiplication
F=np.dot(A,B)# or A @ B
#Transpose
A_transpose=A.T
print("Addition:")
print(C)
print("\nSubstraction:" )
print(D)
print("\nElement-wise Multiplication:")
print(E)
print("\nMatrix Multiplication:")
print(F)
print("\nTranspose:")
print(A_transpose)

Addition:
[[ 5  5]
 [ 5 14]]

Substraction:
[[-1  1]
 [ 3 -4]]

Element-wise Multiplication:
[[ 6  6]
 [ 4 45]]

Matrix Multiplication:
[[ 9 31]
 [17 53]]

Transpose:
[[2 4]
 [3 5]]


In [6]:
import numpy as np
#create a sample matrix
X=np.array([[2,3,4],[5,6,7],[7,8,9]])
#perform SVD
U,S,VT=np.linalg.svd(X)
#Choose the number of components to keep
n_components=2
#Reconstruct the matrix with reduced dimensions
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix(with reduced dimensions:)")
print(X_reconstructed)

Original Matrix:
[[2 3 4]
 [5 6 7]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions:)
[[2. 3. 4.]
 [5. 6. 7.]
 [7. 8. 9.]]
